[package]
name = "irox-graphing"
description = "Graphs (Nodes/Edges) Algorithms, and Graph Drawing"
keywords = ["irox"]
categories = ["algorithms", "data-structures", "mathematics", "visualization"]

version= "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[features]
default = []
egui = ["dep:irox-egui-extras"]

[dependencies]
irox-tools = {workspace = true, features = ["std"]}
irox-units = {workspace = true, features = ["std"]}
irox-geometry = {workspace = true}
irox-structs_derive = {workspace = true}
irox-log = {workspace = true, features = ["std"]}
irox-egui-extras = {workspace = true, features = ["default"], optional = true}

[dev-dependencies]
serde_json = {workspace = true, features = ["preserve_order"] }
serde = {workspace = true, features = ["derive"]}

[[example]]
name = "miserables"
required-features = ["egui"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
