[package]
name = "irox-time"
description = "Date and Time types to manage the inherent complexity of dealing with the fourth dimension."
keywords = ["irox", "date", "time", "iso8601"]
categories = ["date-and-time", "encoding", "parser-implementations", "science", "value-formatting"]
version= "0.5.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[dependencies]
irox-fixedmath.workspace = true
irox-units.workspace = true
irox-tools = { version = "^0", path = "../tools", default-features = false }
irox-enums.workspace = true
serde = {workspace = true, optional = true}

[dev-dependencies]
serde_json = {workspace = true}
serde = {workspace = true, features=["derive"]}

[features]
default = []
std = []
serde = ["dep:serde"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]