[package]
name = "irox-derive-helpers"
description = "Helper traits & functions for the proc_macro crate to aid in writing less complex derive macros."
keywords = ["irox", "proc-macro"]
categories = ["development-tools::procedural-macro-helpers"]
version= "0.1.1"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[features]
syn = ["dep:syn"]

[dependencies]
syn = {workspace = true, optional = true}
irox-tools.workspace = true
