[package]
name = "irox-imagery"
description = "Image processing, manipulation, formats"
keywords = ["irox", "imagery"]
categories = ["graphics", "encoding", "parsing"]
version = "0.1.2"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true
readme = "README.md"

[features]
default = []
std = ["irox-bits/std", "irox-tools/std"]

[lints]
workspace = true

[dependencies]
irox-log = { workspace = true }
irox-bits = { workspace = true }
irox-tools = { workspace = true }
irox-units.workspace = true
irox-carto.workspace = true
irox-types.workspace = true
