[package]
name = "irox-imagery"
description = "Image processing, manipulation, formats"
keywords = ["irox", "imagery"]
categories = ["graphics", "encoding", "parsing"]
version = "0.1.3"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
exclude.workspace = true
repository.workspace = true
readme = "README.md"

[features]
default = []
alloc = ["irox-bits/alloc", "irox-tools/alloc"]
std = ["irox-bits/std", "irox-tools/std", "irox-log/std", "alloc"]
egui = ["dep:egui"]

[lints]
workspace = true

[dependencies]
irox-log = { workspace = true }
irox-bits = { workspace = true }
irox-tools = { workspace = true }
egui = {workspace = true, optional = true}
